apiVersion: v1
kind: Service
metadata:
  name: register-app-service
  namespace: default   # <--- add this
  labels:
    app: register-app
spec:
  selector:
    app: register-app
  ports:
    - port: 80          # service port (external)
      targetPort: 8080  # pod container port
  type: LoadBalancer
